baseURL = 'https://subvxz.pages.dev/'
languageCode = 'en-us'
title = 'Subtitle'
disableFastRender = true
disableLiveReload = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  baseName = "SubVXZ"
[minify]
  minifyOutput = true
